controllers:
    resource: ../src/Controller/
    type: attribute

#Route hello
hello: #nom de la route
    controller: 'App\Controller\HomeController::hello'  #permet de charger le controller et la méthode indiqué
    path: '/hello'  #Url de la route

#Route bye
# bye:
#     controller: 'App\Controller\HomeController::bye'
#     path: '/bye'